export const usersList = [
  {
    id: 1,
    name: "Admin One",
    username: "admin1@gmail.com",
    password: "admin1pwd",
    isLogged: false,
    role: "ADMIN",
  },
  {
    id: 2,
    name: "User One",
    username: "user1@gmail.com",
    password: "user1pwd",
    isLogged: false,
    role: "USER",
  },
  {
    id: 3,
    name: "User Two",
    username: "user2@gmail.com",
    password: "user2pwd",
    isLogged: false,
    role: "USER",
  },
  {
    id: 4,
    name: "User Three",
    username: "user3@gmail.com",
    password: "user3pwd",
    isLogged: false,
    role: "USER",
  },
  {
    id: 5,
    name: "User Four",
    username: "user4@gmail.com",
    password: "user4pwd",
    isLogged: false,
    role: "USER",
  },
];

export const leavesList = [
  {
    username: "user1@gmail.com",
    leaveType: "Earned Leave",
    startDate: "2022-01-09",
    endDate: "2022-01-13",
    leaveCount: 4,
    createdBy: "User One",
    status: "Approved",
    createdAt: 1613332310473,
  },
  {
    username: "user4@gmail.com",
    leaveType: "Sick Leave",
    startDate: "2022-02-04",
    endDate: "2022-02-05",
    leaveCount: 2,
    createdBy: "User Four",
    status: "Pending",
    createdAt: 1613332420653,
  },
  {
    username: "user3@gmail.com",
    leaveType: "Sick Leave",
    startDate: "2022-02-10",
    endDate: "2022-02-11",
    leaveCount: 2,
    createdBy: "User Three",
    status: "Approved",
    createdAt: 1613323220567,
  },
  {
    username: "user3@gmail.com",
    leaveType: "Earned Leave",
    startDate: "2022-01-16",
    endDate: "2022-01-17",
    leaveCount: 2,
    createdBy: "User Three",
    status: "Approved",
    createdAt: 1613332345623,
  },
  {
    username: "user2@gmail.com",
    leaveType: "Earned Leave",
    startDate: "2022-01-15",
    endDate: "2022-01-20",
    leaveCount: 6,
    createdBy: "User Two",
    status: "Pending",
    createdAt: 1613332337845,
  },
  {
    username: "user1@gmail.com",
    leaveType: "Sick Leave",
    startDate: "2022-02-09",
    endDate: "2022-02-10",
    leaveCount: 2,
    createdBy: "User One",
    status: "Approved",
    createdAt: 1613332378326,
  },
];
